version: '3'

services:
  
  controller:
    volumes:
      - ./ansible:/ansible:0770
    build:
      context: .
      dockerfile: Dockerfile.controller
    hostname: controller
    tty: true

  hosta:
    build:
      context: .
      dockerfile: Dockerfile.host
    hostname: hosta
    